package main

import (
	"context"
	"fmt"
	"log"
	"net"

	// Import the magic code generated by the Robot
	// Note: "grpc-shop" is the name we gave in 'go mod init'
	pb "grpc-shop/pb/proto" 
	"google.golang.org/grpc"
)

// server is our Cook. It looks like the 'Unimplemented' struct 
// the Robot created, but we will add real brains to it.
type server struct {
	pb.UnimplementedProductInfoServer
}

// GetProduct is the actual cooking method
func (s *server) GetProduct(ctx context.Context, in *pb.ProductID) (*pb.Product, error) {
	fmt.Printf("Order received for ID: %s\n", in.GetValue())

	// Simple logic: We just return a dummy Biryani for now
	return &pb.Product{
		Id:    in.GetValue(),
		Name:  "Kacchi Biryani",
		Price: 450.00,
	}, nil
}

func main() {
	// 1. Open the Shop Door (Listen on port 50051)
	listener, err := net.Listen("tcp", ":50051")
	if err != nil {
		log.Fatalf("Failed to listen: %v", err)
	}

	// 2. Hire the gRPC Server Manager
	s := grpc.NewServer()

	// 3. Register our Cook (server) with the Manager
	pb.RegisterProductInfoServer(s, &server{})

	fmt.Println("🚀 Shop is open at port 50051...")
	
	// 4. Start serving!
	if err := s.Serve(listener); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}