// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/stream/stream.proto

package stream

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamCalculator_Adder_FullMethodName             = "/stream.StreamCalculator/Adder"
	StreamCalculator_GenarateFibonacci_FullMethodName = "/stream.StreamCalculator/GenarateFibonacci"
)

// StreamCalculatorClient is the client API for StreamCalculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Server Streaming Calculator Service
type StreamCalculatorClient interface {
	// Unary RPC
	Adder(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	// Server Streaming RPC
	GenarateFibonacci(ctx context.Context, in *FibonacciRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FibonacciResponse], error)
}

type streamCalculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamCalculatorClient(cc grpc.ClientConnInterface) StreamCalculatorClient {
	return &streamCalculatorClient{cc}
}

func (c *streamCalculatorClient) Adder(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, StreamCalculator_Adder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamCalculatorClient) GenarateFibonacci(ctx context.Context, in *FibonacciRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FibonacciResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamCalculator_ServiceDesc.Streams[0], StreamCalculator_GenarateFibonacci_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FibonacciRequest, FibonacciResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamCalculator_GenarateFibonacciClient = grpc.ServerStreamingClient[FibonacciResponse]

// StreamCalculatorServer is the server API for StreamCalculator service.
// All implementations must embed UnimplementedStreamCalculatorServer
// for forward compatibility.
//
// Server Streaming Calculator Service
type StreamCalculatorServer interface {
	// Unary RPC
	Adder(context.Context, *AddRequest) (*AddResponse, error)
	// Server Streaming RPC
	GenarateFibonacci(*FibonacciRequest, grpc.ServerStreamingServer[FibonacciResponse]) error
	mustEmbedUnimplementedStreamCalculatorServer()
}

// UnimplementedStreamCalculatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamCalculatorServer struct{}

func (UnimplementedStreamCalculatorServer) Adder(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Adder not implemented")
}
func (UnimplementedStreamCalculatorServer) GenarateFibonacci(*FibonacciRequest, grpc.ServerStreamingServer[FibonacciResponse]) error {
	return status.Error(codes.Unimplemented, "method GenarateFibonacci not implemented")
}
func (UnimplementedStreamCalculatorServer) mustEmbedUnimplementedStreamCalculatorServer() {}
func (UnimplementedStreamCalculatorServer) testEmbeddedByValue()                          {}

// UnsafeStreamCalculatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamCalculatorServer will
// result in compilation errors.
type UnsafeStreamCalculatorServer interface {
	mustEmbedUnimplementedStreamCalculatorServer()
}

func RegisterStreamCalculatorServer(s grpc.ServiceRegistrar, srv StreamCalculatorServer) {
	// If the following call panics, it indicates UnimplementedStreamCalculatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamCalculator_ServiceDesc, srv)
}

func _StreamCalculator_Adder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamCalculatorServer).Adder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamCalculator_Adder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamCalculatorServer).Adder(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamCalculator_GenarateFibonacci_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FibonacciRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamCalculatorServer).GenarateFibonacci(m, &grpc.GenericServerStream[FibonacciRequest, FibonacciResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamCalculator_GenarateFibonacciServer = grpc.ServerStreamingServer[FibonacciResponse]

// StreamCalculator_ServiceDesc is the grpc.ServiceDesc for StreamCalculator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamCalculator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stream.StreamCalculator",
	HandlerType: (*StreamCalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Adder",
			Handler:    _StreamCalculator_Adder_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenarateFibonacci",
			Handler:       _StreamCalculator_GenarateFibonacci_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/stream/stream.proto",
}
