// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/stream/stream.proto

package stream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int32                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int32                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_proto_stream_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_stream_proto_rawDescGZIP(), []int{0}
}

func (x *AddRequest) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *AddRequest) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_proto_stream_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_proto_stream_stream_proto_rawDescGZIP(), []int{1}
}

func (x *AddResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type FibonacciRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             int32                  `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FibonacciRequest) Reset() {
	*x = FibonacciRequest{}
	mi := &file_proto_stream_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FibonacciRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FibonacciRequest) ProtoMessage() {}

func (x *FibonacciRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FibonacciRequest.ProtoReflect.Descriptor instead.
func (*FibonacciRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_stream_proto_rawDescGZIP(), []int{2}
}

func (x *FibonacciRequest) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

type FibonacciResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FibonacciResponse) Reset() {
	*x = FibonacciResponse{}
	mi := &file_proto_stream_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FibonacciResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FibonacciResponse) ProtoMessage() {}

func (x *FibonacciResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FibonacciResponse.ProtoReflect.Descriptor instead.
func (*FibonacciResponse) Descriptor() ([]byte, []int) {
	return file_proto_stream_stream_proto_rawDescGZIP(), []int{3}
}

func (x *FibonacciResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type NumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberRequest) Reset() {
	*x = NumberRequest{}
	mi := &file_proto_stream_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberRequest) ProtoMessage() {}

func (x *NumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberRequest.ProtoReflect.Descriptor instead.
func (*NumberRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_stream_proto_rawDescGZIP(), []int{4}
}

func (x *NumberRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type NumberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sunber        int32                  `protobuf:"varint,1,opt,name=sunber,proto3" json:"sunber,omitempty"`
	Sum           int32                  `protobuf:"varint,2,opt,name=sum,proto3" json:"sum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberResponse) Reset() {
	*x = NumberResponse{}
	mi := &file_proto_stream_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberResponse) ProtoMessage() {}

func (x *NumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberResponse.ProtoReflect.Descriptor instead.
func (*NumberResponse) Descriptor() ([]byte, []int) {
	return file_proto_stream_stream_proto_rawDescGZIP(), []int{5}
}

func (x *NumberResponse) GetSunber() int32 {
	if x != nil {
		return x.Sunber
	}
	return 0
}

func (x *NumberResponse) GetSum() int32 {
	if x != nil {
		return x.Sum
	}
	return 0
}

var File_proto_stream_stream_proto protoreflect.FileDescriptor

const file_proto_stream_stream_proto_rawDesc = "" +
	"\n" +
	"\x19proto/stream/stream.proto\x12\x06stream\"(\n" +
	"\n" +
	"AddRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x05R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x05R\x01b\"%\n" +
	"\vAddResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\" \n" +
	"\x10FibonacciRequest\x12\f\n" +
	"\x01n\x18\x01 \x01(\x05R\x01n\")\n" +
	"\x11FibonacciResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\"'\n" +
	"\rNumberRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\":\n" +
	"\x0eNumberResponse\x12\x16\n" +
	"\x06sunber\x18\x01 \x01(\x05R\x06sunber\x12\x10\n" +
	"\x03sum\x18\x02 \x01(\x05R\x03sum2\xd0\x01\n" +
	"\x10StreamCalculator\x120\n" +
	"\x05Adder\x12\x12.stream.AddRequest\x1a\x13.stream.AddResponse\x12J\n" +
	"\x11GenarateFibonacci\x12\x18.stream.FibonacciRequest\x1a\x19.stream.FibonacciResponse0\x01\x12>\n" +
	"\vSendNumbers\x12\x15.stream.NumberRequest\x1a\x16.stream.NumberResponse(\x01B?Z=github.com/rifate-nur-shawn/gRpc-microservice/pb/proto/streamb\x06proto3"

var (
	file_proto_stream_stream_proto_rawDescOnce sync.Once
	file_proto_stream_stream_proto_rawDescData []byte
)

func file_proto_stream_stream_proto_rawDescGZIP() []byte {
	file_proto_stream_stream_proto_rawDescOnce.Do(func() {
		file_proto_stream_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stream_stream_proto_rawDesc), len(file_proto_stream_stream_proto_rawDesc)))
	})
	return file_proto_stream_stream_proto_rawDescData
}

var file_proto_stream_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_stream_stream_proto_goTypes = []any{
	(*AddRequest)(nil),        // 0: stream.AddRequest
	(*AddResponse)(nil),       // 1: stream.AddResponse
	(*FibonacciRequest)(nil),  // 2: stream.FibonacciRequest
	(*FibonacciResponse)(nil), // 3: stream.FibonacciResponse
	(*NumberRequest)(nil),     // 4: stream.NumberRequest
	(*NumberResponse)(nil),    // 5: stream.NumberResponse
}
var file_proto_stream_stream_proto_depIdxs = []int32{
	0, // 0: stream.StreamCalculator.Adder:input_type -> stream.AddRequest
	2, // 1: stream.StreamCalculator.GenarateFibonacci:input_type -> stream.FibonacciRequest
	4, // 2: stream.StreamCalculator.SendNumbers:input_type -> stream.NumberRequest
	1, // 3: stream.StreamCalculator.Adder:output_type -> stream.AddResponse
	3, // 4: stream.StreamCalculator.GenarateFibonacci:output_type -> stream.FibonacciResponse
	5, // 5: stream.StreamCalculator.SendNumbers:output_type -> stream.NumberResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_stream_stream_proto_init() }
func file_proto_stream_stream_proto_init() {
	if File_proto_stream_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stream_stream_proto_rawDesc), len(file_proto_stream_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stream_stream_proto_goTypes,
		DependencyIndexes: file_proto_stream_stream_proto_depIdxs,
		MessageInfos:      file_proto_stream_stream_proto_msgTypes,
	}.Build()
	File_proto_stream_stream_proto = out.File
	file_proto_stream_stream_proto_goTypes = nil
	file_proto_stream_stream_proto_depIdxs = nil
}
