// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/farewell/farewell.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FarewellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FarewellRequest) Reset() {
	*x = FarewellRequest{}
	mi := &file_proto_farewell_farewell_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FarewellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarewellRequest) ProtoMessage() {}

func (x *FarewellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_farewell_farewell_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarewellRequest.ProtoReflect.Descriptor instead.
func (*FarewellRequest) Descriptor() ([]byte, []int) {
	return file_proto_farewell_farewell_proto_rawDescGZIP(), []int{0}
}

func (x *FarewellRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FarewellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FarewellResponse) Reset() {
	*x = FarewellResponse{}
	mi := &file_proto_farewell_farewell_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FarewellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarewellResponse) ProtoMessage() {}

func (x *FarewellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_farewell_farewell_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarewellResponse.ProtoReflect.Descriptor instead.
func (*FarewellResponse) Descriptor() ([]byte, []int) {
	return file_proto_farewell_farewell_proto_rawDescGZIP(), []int{1}
}

func (x *FarewellResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_farewell_farewell_proto protoreflect.FileDescriptor

const file_proto_farewell_farewell_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/farewell/farewell.proto\x12\x02pb\"%\n" +
	"\x0fFarewellRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x10FarewellResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2=\n" +
	"\bFarewell\x121\n" +
	"\x04Fare\x12\x13.pb.FarewellRequest\x1a\x14.pb.FarewellResponseB2Z0github.com/rifate-nur-shawn/gRpc-microservice/pbb\x06proto3"

var (
	file_proto_farewell_farewell_proto_rawDescOnce sync.Once
	file_proto_farewell_farewell_proto_rawDescData []byte
)

func file_proto_farewell_farewell_proto_rawDescGZIP() []byte {
	file_proto_farewell_farewell_proto_rawDescOnce.Do(func() {
		file_proto_farewell_farewell_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_farewell_farewell_proto_rawDesc), len(file_proto_farewell_farewell_proto_rawDesc)))
	})
	return file_proto_farewell_farewell_proto_rawDescData
}

var file_proto_farewell_farewell_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_farewell_farewell_proto_goTypes = []any{
	(*FarewellRequest)(nil),  // 0: pb.FarewellRequest
	(*FarewellResponse)(nil), // 1: pb.FarewellResponse
}
var file_proto_farewell_farewell_proto_depIdxs = []int32{
	0, // 0: pb.Farewell.Fare:input_type -> pb.FarewellRequest
	1, // 1: pb.Farewell.Fare:output_type -> pb.FarewellResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_farewell_farewell_proto_init() }
func file_proto_farewell_farewell_proto_init() {
	if File_proto_farewell_farewell_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_farewell_farewell_proto_rawDesc), len(file_proto_farewell_farewell_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_farewell_farewell_proto_goTypes,
		DependencyIndexes: file_proto_farewell_farewell_proto_depIdxs,
		MessageInfos:      file_proto_farewell_farewell_proto_msgTypes,
	}.Build()
	File_proto_farewell_farewell_proto = out.File
	file_proto_farewell_farewell_proto_goTypes = nil
	file_proto_farewell_farewell_proto_depIdxs = nil
}
