// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/farewell/farewell.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Farewell_Fare_FullMethodName = "/pb.Farewell/Fare"
)

// FarewellClient is the client API for Farewell service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition
type FarewellClient interface {
	// Sends a farewell message
	Fare(ctx context.Context, in *FarewellRequest, opts ...grpc.CallOption) (*FarewellResponse, error)
}

type farewellClient struct {
	cc grpc.ClientConnInterface
}

func NewFarewellClient(cc grpc.ClientConnInterface) FarewellClient {
	return &farewellClient{cc}
}

func (c *farewellClient) Fare(ctx context.Context, in *FarewellRequest, opts ...grpc.CallOption) (*FarewellResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FarewellResponse)
	err := c.cc.Invoke(ctx, Farewell_Fare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FarewellServer is the server API for Farewell service.
// All implementations must embed UnimplementedFarewellServer
// for forward compatibility.
//
// Service definition
type FarewellServer interface {
	// Sends a farewell message
	Fare(context.Context, *FarewellRequest) (*FarewellResponse, error)
	mustEmbedUnimplementedFarewellServer()
}

// UnimplementedFarewellServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFarewellServer struct{}

func (UnimplementedFarewellServer) Fare(context.Context, *FarewellRequest) (*FarewellResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Fare not implemented")
}
func (UnimplementedFarewellServer) mustEmbedUnimplementedFarewellServer() {}
func (UnimplementedFarewellServer) testEmbeddedByValue()                  {}

// UnsafeFarewellServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FarewellServer will
// result in compilation errors.
type UnsafeFarewellServer interface {
	mustEmbedUnimplementedFarewellServer()
}

func RegisterFarewellServer(s grpc.ServiceRegistrar, srv FarewellServer) {
	// If the following call panics, it indicates UnimplementedFarewellServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Farewell_ServiceDesc, srv)
}

func _Farewell_Fare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FarewellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarewellServer).Fare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Farewell_Fare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarewellServer).Fare(ctx, req.(*FarewellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Farewell_ServiceDesc is the grpc.ServiceDesc for Farewell service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Farewell_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Farewell",
	HandlerType: (*FarewellServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fare",
			Handler:    _Farewell_Fare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/farewell/farewell.proto",
}
