// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/gpu_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GpuDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manufacturer  string                 `protobuf:"bytes,1,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Architecture  string                 `protobuf:"bytes,3,opt,name=architecture,proto3" json:"architecture,omitempty"`
	BaseClockGhz  float64                `protobuf:"fixed64,4,opt,name=base_clock_ghz,json=baseClockGhz,proto3" json:"base_clock_ghz,omitempty"`
	BoostClockGhz float64                `protobuf:"fixed64,5,opt,name=boost_clock_ghz,json=boostClockGhz,proto3" json:"boost_clock_ghz,omitempty"`
	Memory        *Memory                `protobuf:"bytes,6,opt,name=memory,proto3" json:"memory,omitempty"`
	VramBusBits   uint32                 `protobuf:"varint,7,opt,name=vram_bus_bits,json=vramBusBits,proto3" json:"vram_bus_bits,omitempty"`
	Outputs       []string               `protobuf:"bytes,8,rep,name=outputs,proto3" json:"outputs,omitempty"`
	IsIntegrated  bool                   `protobuf:"varint,9,opt,name=is_integrated,json=isIntegrated,proto3" json:"is_integrated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpuDetails) Reset() {
	*x = GpuDetails{}
	mi := &file_proto_gpu_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuDetails) ProtoMessage() {}

func (x *GpuDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpu_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuDetails.ProtoReflect.Descriptor instead.
func (*GpuDetails) Descriptor() ([]byte, []int) {
	return file_proto_gpu_message_proto_rawDescGZIP(), []int{0}
}

func (x *GpuDetails) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *GpuDetails) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GpuDetails) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *GpuDetails) GetBaseClockGhz() float64 {
	if x != nil {
		return x.BaseClockGhz
	}
	return 0
}

func (x *GpuDetails) GetBoostClockGhz() float64 {
	if x != nil {
		return x.BoostClockGhz
	}
	return 0
}

func (x *GpuDetails) GetMemory() *Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *GpuDetails) GetVramBusBits() uint32 {
	if x != nil {
		return x.VramBusBits
	}
	return 0
}

func (x *GpuDetails) GetOutputs() []string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *GpuDetails) GetIsIntegrated() bool {
	if x != nil {
		return x.IsIntegrated
	}
	return false
}

var File_proto_gpu_message_proto protoreflect.FileDescriptor

const file_proto_gpu_message_proto_rawDesc = "" +
	"\n" +
	"\x17proto/gpu_message.proto\x12\x02pb\x1a\x1aproto/memory_message.proto\"\xbf\x02\n" +
	"\n" +
	"GpuDetails\x12\"\n" +
	"\fmanufacturer\x18\x01 \x01(\tR\fmanufacturer\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\"\n" +
	"\farchitecture\x18\x03 \x01(\tR\farchitecture\x12$\n" +
	"\x0ebase_clock_ghz\x18\x04 \x01(\x01R\fbaseClockGhz\x12&\n" +
	"\x0fboost_clock_ghz\x18\x05 \x01(\x01R\rboostClockGhz\x12\"\n" +
	"\x06memory\x18\x06 \x01(\v2\n" +
	".pb.MemoryR\x06memory\x12\"\n" +
	"\rvram_bus_bits\x18\a \x01(\rR\vvramBusBits\x12\x18\n" +
	"\aoutputs\x18\b \x03(\tR\aoutputs\x12#\n" +
	"\ris_integrated\x18\t \x01(\bR\fisIntegratedB2Z0github.com/rifate-nur-shawn/gRpc-microservice/pbb\x06proto3"

var (
	file_proto_gpu_message_proto_rawDescOnce sync.Once
	file_proto_gpu_message_proto_rawDescData []byte
)

func file_proto_gpu_message_proto_rawDescGZIP() []byte {
	file_proto_gpu_message_proto_rawDescOnce.Do(func() {
		file_proto_gpu_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gpu_message_proto_rawDesc), len(file_proto_gpu_message_proto_rawDesc)))
	})
	return file_proto_gpu_message_proto_rawDescData
}

var file_proto_gpu_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_gpu_message_proto_goTypes = []any{
	(*GpuDetails)(nil), // 0: pb.GpuDetails
	(*Memory)(nil),     // 1: pb.Memory
}
var file_proto_gpu_message_proto_depIdxs = []int32{
	1, // 0: pb.GpuDetails.memory:type_name -> pb.Memory
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_gpu_message_proto_init() }
func file_proto_gpu_message_proto_init() {
	if File_proto_gpu_message_proto != nil {
		return
	}
	file_proto_memory_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gpu_message_proto_rawDesc), len(file_proto_gpu_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_gpu_message_proto_goTypes,
		DependencyIndexes: file_proto_gpu_message_proto_depIdxs,
		MessageInfos:      file_proto_gpu_message_proto_msgTypes,
	}.Build()
	File_proto_gpu_message_proto = out.File
	file_proto_gpu_message_proto_goTypes = nil
	file_proto_gpu_message_proto_depIdxs = nil
}
