// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/laptop_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Display struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Technology    string                 `protobuf:"bytes,1,opt,name=technology,proto3" json:"technology,omitempty"`
	SizeInch      float64                `protobuf:"fixed64,2,opt,name=size_inch,json=sizeInch,proto3" json:"size_inch,omitempty"`
	RefreshRateHz float64                `protobuf:"fixed64,3,opt,name=refresh_rate_hz,json=refreshRateHz,proto3" json:"refresh_rate_hz,omitempty"`
	Touchscreen   bool                   `protobuf:"varint,4,opt,name=touchscreen,proto3" json:"touchscreen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Display) Reset() {
	*x = Display{}
	mi := &file_proto_laptop_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Display) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Display) ProtoMessage() {}

func (x *Display) ProtoReflect() protoreflect.Message {
	mi := &file_proto_laptop_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Display.ProtoReflect.Descriptor instead.
func (*Display) Descriptor() ([]byte, []int) {
	return file_proto_laptop_message_proto_rawDescGZIP(), []int{0}
}

func (x *Display) GetTechnology() string {
	if x != nil {
		return x.Technology
	}
	return ""
}

func (x *Display) GetSizeInch() float64 {
	if x != nil {
		return x.SizeInch
	}
	return 0
}

func (x *Display) GetRefreshRateHz() float64 {
	if x != nil {
		return x.RefreshRateHz
	}
	return 0
}

func (x *Display) GetTouchscreen() bool {
	if x != nil {
		return x.Touchscreen
	}
	return false
}

type Laptop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manufacturer  string                 `protobuf:"bytes,1,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Cpu           *Cpu                   `protobuf:"bytes,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Gpu           *GpuDetails            `protobuf:"bytes,4,opt,name=gpu,proto3" json:"gpu,omitempty"`
	Memory        *Memory                `protobuf:"bytes,5,opt,name=memory,proto3" json:"memory,omitempty"`
	RamGb         uint32                 `protobuf:"varint,6,opt,name=ram_gb,json=ramGb,proto3" json:"ram_gb,omitempty"`
	Display       *Display               `protobuf:"bytes,7,opt,name=display,proto3" json:"display,omitempty"`
	WeightKg      float64                `protobuf:"fixed64,8,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	Ports         []string               `protobuf:"bytes,9,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Laptop) Reset() {
	*x = Laptop{}
	mi := &file_proto_laptop_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Laptop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Laptop) ProtoMessage() {}

func (x *Laptop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_laptop_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Laptop.ProtoReflect.Descriptor instead.
func (*Laptop) Descriptor() ([]byte, []int) {
	return file_proto_laptop_message_proto_rawDescGZIP(), []int{1}
}

func (x *Laptop) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *Laptop) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Laptop) GetCpu() *Cpu {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *Laptop) GetGpu() *GpuDetails {
	if x != nil {
		return x.Gpu
	}
	return nil
}

func (x *Laptop) GetMemory() *Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *Laptop) GetRamGb() uint32 {
	if x != nil {
		return x.RamGb
	}
	return 0
}

func (x *Laptop) GetDisplay() *Display {
	if x != nil {
		return x.Display
	}
	return nil
}

func (x *Laptop) GetWeightKg() float64 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

func (x *Laptop) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

var File_proto_laptop_message_proto protoreflect.FileDescriptor

const file_proto_laptop_message_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/laptop_message.proto\x12\x02pb\x1a\x1dproto/processor_message.proto\x1a\x1aproto/memory_message.proto\x1a\x17proto/gpu_message.proto\"\x90\x01\n" +
	"\aDisplay\x12\x1e\n" +
	"\n" +
	"technology\x18\x01 \x01(\tR\n" +
	"technology\x12\x1b\n" +
	"\tsize_inch\x18\x02 \x01(\x01R\bsizeInch\x12&\n" +
	"\x0frefresh_rate_hz\x18\x03 \x01(\x01R\rrefreshRateHz\x12 \n" +
	"\vtouchscreen\x18\x04 \x01(\bR\vtouchscreen\"\x94\x02\n" +
	"\x06Laptop\x12\"\n" +
	"\fmanufacturer\x18\x01 \x01(\tR\fmanufacturer\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x19\n" +
	"\x03cpu\x18\x03 \x01(\v2\a.pb.CpuR\x03cpu\x12 \n" +
	"\x03gpu\x18\x04 \x01(\v2\x0e.pb.GpuDetailsR\x03gpu\x12\"\n" +
	"\x06memory\x18\x05 \x01(\v2\n" +
	".pb.MemoryR\x06memory\x12\x15\n" +
	"\x06ram_gb\x18\x06 \x01(\rR\x05ramGb\x12%\n" +
	"\adisplay\x18\a \x01(\v2\v.pb.DisplayR\adisplay\x12\x1b\n" +
	"\tweight_kg\x18\b \x01(\x01R\bweightKg\x12\x14\n" +
	"\x05ports\x18\t \x03(\tR\x05portsB2Z0github.com/rifate-nur-shawn/gRpc-microservice/pbb\x06proto3"

var (
	file_proto_laptop_message_proto_rawDescOnce sync.Once
	file_proto_laptop_message_proto_rawDescData []byte
)

func file_proto_laptop_message_proto_rawDescGZIP() []byte {
	file_proto_laptop_message_proto_rawDescOnce.Do(func() {
		file_proto_laptop_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_laptop_message_proto_rawDesc), len(file_proto_laptop_message_proto_rawDesc)))
	})
	return file_proto_laptop_message_proto_rawDescData
}

var file_proto_laptop_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_laptop_message_proto_goTypes = []any{
	(*Display)(nil),    // 0: pb.Display
	(*Laptop)(nil),     // 1: pb.Laptop
	(*Cpu)(nil),        // 2: pb.Cpu
	(*GpuDetails)(nil), // 3: pb.GpuDetails
	(*Memory)(nil),     // 4: pb.Memory
}
var file_proto_laptop_message_proto_depIdxs = []int32{
	2, // 0: pb.Laptop.cpu:type_name -> pb.Cpu
	3, // 1: pb.Laptop.gpu:type_name -> pb.GpuDetails
	4, // 2: pb.Laptop.memory:type_name -> pb.Memory
	0, // 3: pb.Laptop.display:type_name -> pb.Display
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_laptop_message_proto_init() }
func file_proto_laptop_message_proto_init() {
	if File_proto_laptop_message_proto != nil {
		return
	}
	file_proto_processor_message_proto_init()
	file_proto_memory_message_proto_init()
	file_proto_gpu_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_laptop_message_proto_rawDesc), len(file_proto_laptop_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_laptop_message_proto_goTypes,
		DependencyIndexes: file_proto_laptop_message_proto_depIdxs,
		MessageInfos:      file_proto_laptop_message_proto_msgTypes,
	}.Build()
	File_proto_laptop_message_proto = out.File
	file_proto_laptop_message_proto_goTypes = nil
	file_proto_laptop_message_proto_depIdxs = nil
}
