// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/processor_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cpu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NumberCores   uint32                 `protobuf:"varint,3,opt,name=number_cores,json=numberCores,proto3" json:"number_cores,omitempty"`
	NumberThreads uint32                 `protobuf:"varint,4,opt,name=number_threads,json=numberThreads,proto3" json:"number_threads,omitempty"`
	MinGhz        float64                `protobuf:"fixed64,5,opt,name=min_ghz,json=minGhz,proto3" json:"min_ghz,omitempty"`
	MaxGhz        float64                `protobuf:"fixed64,6,opt,name=max_ghz,json=maxGhz,proto3" json:"max_ghz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cpu) Reset() {
	*x = Cpu{}
	mi := &file_proto_processor_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cpu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cpu) ProtoMessage() {}

func (x *Cpu) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cpu.ProtoReflect.Descriptor instead.
func (*Cpu) Descriptor() ([]byte, []int) {
	return file_proto_processor_message_proto_rawDescGZIP(), []int{0}
}

func (x *Cpu) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Cpu) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cpu) GetNumberCores() uint32 {
	if x != nil {
		return x.NumberCores
	}
	return 0
}

func (x *Cpu) GetNumberThreads() uint32 {
	if x != nil {
		return x.NumberThreads
	}
	return 0
}

func (x *Cpu) GetMinGhz() float64 {
	if x != nil {
		return x.MinGhz
	}
	return 0
}

func (x *Cpu) GetMaxGhz() float64 {
	if x != nil {
		return x.MaxGhz
	}
	return 0
}

type Gpu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MinGhz        float64                `protobuf:"fixed64,3,opt,name=min_ghz,json=minGhz,proto3" json:"min_ghz,omitempty"`
	MaxGhz        float64                `protobuf:"fixed64,4,opt,name=max_ghz,json=maxGhz,proto3" json:"max_ghz,omitempty"`
	Memory        *Memory                `protobuf:"bytes,5,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gpu) Reset() {
	*x = Gpu{}
	mi := &file_proto_processor_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gpu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gpu) ProtoMessage() {}

func (x *Gpu) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gpu.ProtoReflect.Descriptor instead.
func (*Gpu) Descriptor() ([]byte, []int) {
	return file_proto_processor_message_proto_rawDescGZIP(), []int{1}
}

func (x *Gpu) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Gpu) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Gpu) GetMinGhz() float64 {
	if x != nil {
		return x.MinGhz
	}
	return 0
}

func (x *Gpu) GetMaxGhz() float64 {
	if x != nil {
		return x.MaxGhz
	}
	return 0
}

func (x *Gpu) GetMemory() *Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

var File_proto_processor_message_proto protoreflect.FileDescriptor

const file_proto_processor_message_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/processor_message.proto\x12\x02pb\x1a\x1aproto/memory_message.proto\"\xab\x01\n" +
	"\x03Cpu\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fnumber_cores\x18\x03 \x01(\rR\vnumberCores\x12%\n" +
	"\x0enumber_threads\x18\x04 \x01(\rR\rnumberThreads\x12\x17\n" +
	"\amin_ghz\x18\x05 \x01(\x01R\x06minGhz\x12\x17\n" +
	"\amax_ghz\x18\x06 \x01(\x01R\x06maxGhz\"\x85\x01\n" +
	"\x03Gpu\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\amin_ghz\x18\x03 \x01(\x01R\x06minGhz\x12\x17\n" +
	"\amax_ghz\x18\x04 \x01(\x01R\x06maxGhz\x12\"\n" +
	"\x06memory\x18\x05 \x01(\v2\n" +
	".pb.MemoryR\x06memoryB2Z0github.com/rifate-nur-shawn/gRpc-microservice/pbb\x06proto3"

var (
	file_proto_processor_message_proto_rawDescOnce sync.Once
	file_proto_processor_message_proto_rawDescData []byte
)

func file_proto_processor_message_proto_rawDescGZIP() []byte {
	file_proto_processor_message_proto_rawDescOnce.Do(func() {
		file_proto_processor_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_processor_message_proto_rawDesc), len(file_proto_processor_message_proto_rawDesc)))
	})
	return file_proto_processor_message_proto_rawDescData
}

var file_proto_processor_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_processor_message_proto_goTypes = []any{
	(*Cpu)(nil),    // 0: pb.Cpu
	(*Gpu)(nil),    // 1: pb.Gpu
	(*Memory)(nil), // 2: pb.Memory
}
var file_proto_processor_message_proto_depIdxs = []int32{
	2, // 0: pb.Gpu.memory:type_name -> pb.Memory
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_processor_message_proto_init() }
func file_proto_processor_message_proto_init() {
	if File_proto_processor_message_proto != nil {
		return
	}
	file_proto_memory_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_processor_message_proto_rawDesc), len(file_proto_processor_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_processor_message_proto_goTypes,
		DependencyIndexes: file_proto_processor_message_proto_depIdxs,
		MessageInfos:      file_proto_processor_message_proto_msgTypes,
	}.Build()
	File_proto_processor_message_proto = out.File
	file_proto_processor_message_proto_goTypes = nil
	file_proto_processor_message_proto_depIdxs = nil
}
