// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/memory_message.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Memory_Uint int32

const (
	Memory_UNKNOWN  Memory_Uint = 0
	Memory_BIT      Memory_Uint = 1
	Memory_BYTE     Memory_Uint = 2
	Memory_KILOBYTE Memory_Uint = 3
	Memory_MEGABYTE Memory_Uint = 4
	Memory_GIGABYTE Memory_Uint = 5
	Memory_TERABYTE Memory_Uint = 6
)

// Enum value maps for Memory_Uint.
var (
	Memory_Uint_name = map[int32]string{
		0: "UNKNOWN",
		1: "BIT",
		2: "BYTE",
		3: "KILOBYTE",
		4: "MEGABYTE",
		5: "GIGABYTE",
		6: "TERABYTE",
	}
	Memory_Uint_value = map[string]int32{
		"UNKNOWN":  0,
		"BIT":      1,
		"BYTE":     2,
		"KILOBYTE": 3,
		"MEGABYTE": 4,
		"GIGABYTE": 5,
		"TERABYTE": 6,
	}
)

func (x Memory_Uint) Enum() *Memory_Uint {
	p := new(Memory_Uint)
	*p = x
	return p
}

func (x Memory_Uint) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Memory_Uint) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_memory_message_proto_enumTypes[0].Descriptor()
}

func (Memory_Uint) Type() protoreflect.EnumType {
	return &file_proto_memory_message_proto_enumTypes[0]
}

func (x Memory_Uint) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Memory_Uint.Descriptor instead.
func (Memory_Uint) EnumDescriptor() ([]byte, []int) {
	return file_proto_memory_message_proto_rawDescGZIP(), []int{0, 0}
}

type Memory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         Memory_Uint            `protobuf:"varint,1,opt,name=value,proto3,enum=pb.Memory_Uint" json:"value,omitempty"`
	Unit          Memory_Uint            `protobuf:"varint,2,opt,name=unit,proto3,enum=pb.Memory_Uint" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Memory) Reset() {
	*x = Memory{}
	mi := &file_proto_memory_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memory) ProtoMessage() {}

func (x *Memory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memory.ProtoReflect.Descriptor instead.
func (*Memory) Descriptor() ([]byte, []int) {
	return file_proto_memory_message_proto_rawDescGZIP(), []int{0}
}

func (x *Memory) GetValue() Memory_Uint {
	if x != nil {
		return x.Value
	}
	return Memory_UNKNOWN
}

func (x *Memory) GetUnit() Memory_Uint {
	if x != nil {
		return x.Unit
	}
	return Memory_UNKNOWN
}

var File_proto_memory_message_proto protoreflect.FileDescriptor

const file_proto_memory_message_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/memory_message.proto\x12\x02pb\"\xb4\x01\n" +
	"\x06Memory\x12%\n" +
	"\x05value\x18\x01 \x01(\x0e2\x0f.pb.Memory.UintR\x05value\x12#\n" +
	"\x04unit\x18\x02 \x01(\x0e2\x0f.pb.Memory.UintR\x04unit\"^\n" +
	"\x04Uint\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03BIT\x10\x01\x12\b\n" +
	"\x04BYTE\x10\x02\x12\f\n" +
	"\bKILOBYTE\x10\x03\x12\f\n" +
	"\bMEGABYTE\x10\x04\x12\f\n" +
	"\bGIGABYTE\x10\x05\x12\f\n" +
	"\bTERABYTE\x10\x06B\x03Z\x01.b\x06proto3"

var (
	file_proto_memory_message_proto_rawDescOnce sync.Once
	file_proto_memory_message_proto_rawDescData []byte
)

func file_proto_memory_message_proto_rawDescGZIP() []byte {
	file_proto_memory_message_proto_rawDescOnce.Do(func() {
		file_proto_memory_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_memory_message_proto_rawDesc), len(file_proto_memory_message_proto_rawDesc)))
	})
	return file_proto_memory_message_proto_rawDescData
}

var file_proto_memory_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_memory_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_memory_message_proto_goTypes = []any{
	(Memory_Uint)(0), // 0: pb.Memory.Uint
	(*Memory)(nil),   // 1: pb.Memory
}
var file_proto_memory_message_proto_depIdxs = []int32{
	0, // 0: pb.Memory.value:type_name -> pb.Memory.Uint
	0, // 1: pb.Memory.unit:type_name -> pb.Memory.Uint
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_memory_message_proto_init() }
func file_proto_memory_message_proto_init() {
	if File_proto_memory_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_memory_message_proto_rawDesc), len(file_proto_memory_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_memory_message_proto_goTypes,
		DependencyIndexes: file_proto_memory_message_proto_depIdxs,
		EnumInfos:         file_proto_memory_message_proto_enumTypes,
		MessageInfos:      file_proto_memory_message_proto_msgTypes,
	}.Build()
	File_proto_memory_message_proto = out.File
	file_proto_memory_message_proto_goTypes = nil
	file_proto_memory_message_proto_depIdxs = nil
}
